### ISSUE TITLE
30-add-test-data-to-gladiator-controller

### ISSUE THREAD

**Issue by JaniTuoriniemi** [LexiconGr7-1/gladiator-management-simulator#30]
1. Add Gladiator entity class to gladiator controller as a subclass
fields:
Id
Name
Strength
Health

2. Add json.net nuget package
Decorate gladiator entity class with json decorators.

3. Populate a list of gladiators
Add 10 test gladiators

4. Return json data from actions

**Comment by gamo-code** [comment]
1. Add Gladiator entity class to gladiator controller as a subclass
fields:
Id
Name
Strength
Health

2. Add json.net nuget package
Decorate gladiator entity class with json decorators.

4. Populate a list of gladiators
Add 10 test gladiators

5. Retun json data from actions
